// Generated by supabase_typegen 0.5.1 from GeneratorMetadata version 1.
// Do not edit by hand.
//
// Source schemas: graphql_public, public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'package:supabase_flutter/supabase_flutter.dart';

/// A row of the `players` table, as `select()` reads it with every column.
/// One row per racer with their banana and lap stats
extension type const PlayersRow(Map<String, dynamic> _json) implements Object {
  /// Every banana ever picked up, thrown or not
  int get bananasCollected => _json['bananas_collected'] as int;

  /// Bananas held right now, ready to throw behind the kart
  int get bananasOwned => _json['bananas_owned'] as int;
  String get id => _json['id'] as String;
  int get lapsFinished => _json['laps_finished'] as int;
  String get name => _json['name'] as String;
  int? get points => _json['points'] as int?;
  int get timesSlipped => _json['times_slipped'] as int;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `players`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const PlayersInsert._(Map<String, dynamic> _json)
    implements Object {
  PlayersInsert({
    int? bananasCollected,
    int? bananasOwned,
    required String id,
    int? lapsFinished,
    required String name,
    int? timesSlipped,
    DateTime? updatedAt,
  }) : this._({
         'bananas_collected': ?bananasCollected,
         'bananas_owned': ?bananasOwned,
         'id': id,
         'laps_finished': ?lapsFinished,
         'name': name,
         'times_slipped': ?timesSlipped,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
       });
}

/// Values for updating rows of `players`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const PlayersUpdate._(Map<String, dynamic> _json)
    implements Object {
  PlayersUpdate({
    int? bananasCollected,
    int? bananasOwned,
    String? id,
    int? lapsFinished,
    String? name,
    int? timesSlipped,
    DateTime? updatedAt,
  }) : this._({
         'bananas_collected': ?bananasCollected,
         'bananas_owned': ?bananasOwned,
         'id': ?id,
         'laps_finished': ?lapsFinished,
         'name': ?name,
         'times_slipped': ?timesSlipped,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
       });
}

/// Typed access to the `players` table.
class Players {
  const Players._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<PlayersRow, PlayersInsert, PlayersUpdate>(
    'players',
    PlayersRow.new,
    schema: 'public',
    primaryKey: [id],
  );

  static const bananasCollected = PostgrestColumn<PlayersRow, int>(
    'bananas_collected',
  );
  static const bananasOwned = PostgrestColumn<PlayersRow, int>('bananas_owned');
  static const id = PostgrestColumn<PlayersRow, String>('id');
  static const lapsFinished = PostgrestColumn<PlayersRow, int>('laps_finished');
  static const name = PostgrestColumn<PlayersRow, String>('name');
  static const points = PostgrestNullableColumn<PlayersRow, int>('points');
  static const timesSlipped = PostgrestColumn<PlayersRow, int>('times_slipped');
  static const updatedAt = PostgrestColumn<PlayersRow, DateTime>(
    'updated_at',
    fromJson: _dateTimeFromJson,
  );
}

/// A row of the `scores` table, as `select()` reads it with every column.
extension type const ScoresRow(Map<String, dynamic> _json) implements Object {
  String get id => _json['id'] as String;
  String get name => _json['name'] as String;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);
  int get wins => _json['wins'] as int;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `scores`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const ScoresInsert._(Map<String, dynamic> _json)
    implements Object {
  ScoresInsert({
    required String id,
    required String name,
    DateTime? updatedAt,
    int? wins,
  }) : this._({
         'id': id,
         'name': name,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'wins': ?wins,
       });
}

/// Values for updating rows of `scores`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const ScoresUpdate._(Map<String, dynamic> _json)
    implements Object {
  ScoresUpdate({String? id, String? name, DateTime? updatedAt, int? wins})
    : this._({
        'id': ?id,
        'name': ?name,
        'updated_at': ?updatedAt?.toUtc().toIso8601String(),
        'wins': ?wins,
      });
}

/// Typed access to the `scores` table.
class Scores {
  const Scores._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<ScoresRow, ScoresInsert, ScoresUpdate>(
    'scores',
    ScoresRow.new,
    schema: 'public',
    primaryKey: [id],
  );

  static const id = PostgrestColumn<ScoresRow, String>('id');
  static const name = PostgrestColumn<ScoresRow, String>('name');
  static const updatedAt = PostgrestColumn<ScoresRow, DateTime>(
    'updated_at',
    fromJson: _dateTimeFromJson,
  );
  static const wins = PostgrestColumn<ScoresRow, int>('wins');
}

DateTime _dateTimeFromJson(Object json) => DateTime.parse(json as String);
